---
- name: Create User Accounts on Access Layer Switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Create Local-Admin user on switches
      community.network.exos_config:
        lines:
          - create account admin Local-Admin WGU123