---
- name: Gather VLAN information from ExtremeXOS switches
  hosts: switches
  gather_facts: no
  tasks:
    - name: Get VLAN information
      ansible.netcommon.cli_command:
        command: show vlan
      register: vlan_output

    - name: Append VLAN information to a single file
      lineinfile:
        path: vlan_info_all_switches.txt
        line: "{{ inventory_hostname }}:\n{{ vlan_output.stdout }}"
        create: yes
        state: present